version: "3.3"
services:
  mongo:
    container_name: mc-ten-year-mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mc-ten-year-mongo:/data/db
    ports:
      - 27017:27017
    restart: on-failure
    command: mongod
volumes:
  mc-ten-year-mongo:
